group {
    col.border_active = rgb(249,226,175)        # mauve
    col.border_inactive = rgb(17,17,27)      # surface1
    col.border_locked_active = rgb(f5c2e7) # pink
    col.border_locked_inactive = rgb(313244) # surface0

    groupbar {
        font_family = JetBrains Mono NF
        font_size = 15
        gradients = true
        gradient_round_only_edges = false
        gradient_rounding = 5
        height = 15
        indicator_height = 0
        gaps_in = 0
        gaps_out = 0

        text_color = rgb(249,226,175)           # text
        col.active = rgb(30,30,46)        # mauve
        col.inactive = rgb(17,17,27)      # overlay0
        col.locked_active = rgba(f5c2e7ff) # pink
        col.locked_inactive = rgba(585b70ff) # surface2
    }
}
